Ecommerce/ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]

Ecommerce/ecommerce/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.store, name='store'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout')
]

Ecommerce/ecommerce/store/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True) # Find Below
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.FloatField()
    digital = models.BooleanField(default=False, null=True, blank=False) # this field means if the product is physical or digital

    def __str__(self):
        return self.name

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)

'''
null=True pertains to the database schema, allowing for NULL values in the database, 
while blank=True is related to form validation, enabling fields to be left empty in form submissions.

Use Cases for null=True

Optional Fields: Use null=True for fields that are not required for all instances of the models. For example, a user’s middle name is optional, so you might set null=True for a middle_name field.
Database-level Constraints: When you need to enforce database-level constraints that allow for missing data, such as foreign keys that reference optional records, you can use null=True.

Use Cases for blank=True

Optional Form Fields: Use blank=True when you want to allow users to leave certain form fields empty. For example, a blog post’s introductory title might be optional, so you’d set blank=True for the title field.
Custom Form Validation: If you plan to implement custom validation logic for a field, blank=True can be useful in cases where you want to allow empty values but still perform additional validation checks.


'''

Ecommerce/ecommerce/store/views.py
from django.shortcuts import render

# Create your views here.
def store(request):
    context = {}
    return render(request, 'store/store.html', context)

def cart(request):
    context = {}
    return render(request, 'store/cart.html', context)

def checkout(request):
    context = {}
    return render(request, 'store/checkout.html', context)

Ecommerce/ecommerce/store/templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'store:store' %}">&#x2190; Continue Shopping</a>
            <br>
            <br>
            <table class="table">
                <tr>
                    <th><h5>Items: <strong>3</strong></h5></th>
                    <th><h5>Total: <strong>$43</strong></h5></th>
                    <th>
                        <a style="float:right; margin:5px" class="btn btn-success" href="{% url 'store:checkout' %}">Checkout</a>
                    </th>
                </tr>
            </table>
        </div>

        <br>

        <div class="box-element">
            <div class="cart-row">
                <div style="flex:2"></div>
                <div style="flex:2"><strong>Item</strong></div>
                <div style="flex:1"><strong>Price</strong></div>
                <div style="flex:1"><strong>Quantity</strong></div>
                <div style="flex:1"><strong>Total</strong></div>
            </div>

            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src="{% static 'images/placeholder.png' %}"></div>
                <div style="flex:2">Product 1</div>
                <div style="flex:1">$20</div>
                <div style="flex:1">
                    <p class="quantity">2</p>
                    <div class="quantity">
                        <img class="chg-quantity" src="{% static  'images/arrow-up.png' %}">
                
                        <img class="chg-quantity" src="{% static  'images/arrow-down.png' %}">
                    </div>
                </div>
                <div style="flex:1"><p>$32</p></div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

Ecommerce/ecommerce/store/templates/store/checkout.html
{% extends 'store/main.html' %}
{% load static %}

{% block content %}
<div class="row">
    <div class="col-lg-6">
        <div class="box-element" id="form-wrapper">
            <form id="form">
                <div id="user-infor">
                    <div class="form-field">
                        <input required class="form-control" type="text" name="name" placeholder="Name..">
                    </div>
                    <div class="form-field">
                        <input required class="form-control" type="email" name="email" placeholder="Email..">
                    </div>
                </div>
                <div id="shipping-info">
                    <hr>
						<p>Shipping Information:</p>
						<hr>
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="City..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="State..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="country" placeholder="Zip code..">
						</div>
                </div>
                <hr>
                <input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
            </form>
        </div>
        <br>
        <div class="box-element hidden" id="payment-info">
            <small>Paypal Options</small>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="box-element">
            <a  class="btn btn-outline-dark" href="{% url 'store:cart' %}">&#x2190; Back to Cart</a>
            <hr>
            <h3>Order Summary</h3>
            <hr>
            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src="{% static 'images/placeholder.png' %}"></div>
                <div style="flex:2"><p>Product 1</p></div>
                <div style="flex:1"><p>$20.00</p></div>
                <div style="flex:1"><p>x2</p></div>
            </div>
            <h5>Items:   2</h5>
            <h5>Total:   $4</h5>
        </div>
    </div>
</div>
{% endblock content %}

Ecommerce/ecommerce/store/templates/store/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    
    <title>Ecommerce</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'store:store' %}">Ecom</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'store:store' %}">Store <span class="sr-only">(current)</span></a>
            </li>
          </ul>
            <div class="form-inline my-2 my-lg-0">
                <a href="#"class="btn btn-warning">Login</a>
                
                <a href="{% url 'store:cart' %}">
                <img  id="cart-icon" src="{% static 'images/cart.png' %}">
                </a>
                <p id="cart-total">0</p>
            </div>
        </div>
      </nav>

    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
    
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

Ecommerce/ecommerce/store/templates/store/store.html
{% extends 'store/main.html' %}
{% load static %}

{% block content %}
<div class="row">
    <div class="col-lg-4">
        <img class="thumbnail" src="{% static 'images/placeholder.png' %}">
        <div class="box-element product">
            <h6><strong>Product</strong></h6>
            <hr>
            <button class="btn btn-outline-secondary add-btn">Add to Cart</button>
            <a class="btn btn-outline-success" href="#">View</a>
            <h4 style="float:right">$20</h4>
        </div>
    </div>
    <div class="col-lg-4">
        <img class="thumbnail" src="{% static 'images/placeholder.png' %}">
        <div class="box-element product">
            <h6><strong>Product</strong></h6>
            <hr>
            <button class="btn btn-outline-secondary add-btn">Add to Cart</button>
            <a class="btn btn-outline-success" href="#">View</a>
            <h4 style="float:right">$20</h4>
        </div>
    </div>
    <div class="col-lg-4">
        <img class="thumbnail" src="{% static 'images/placeholder.png' %}">
        <div class="box-element product">
            <h6><strong>Product</strong></h6>
            <hr>
            <button class="btn btn-outline-secondary add-btn">Add to Cart</button>
            <a class="btn btn-outline-success" href="#">View</a>
            <h4 style="float:right">$20</h4>
        </div>
    </div>
</div>
{% endblock content%}